"""Shared data models for testprotocols."""

from __future__ import annotations

from testprotocols.models.device_management import (
    EventLogEntry,
    MemoryUtilization,
    ProcessInfo,
    SyslogSeverity,
)
from testprotocols.models.dhcp import DhcpLeaseObservation, DHCPTraceData, DHCPV6TraceData
from testprotocols.models.emission import EmitResult, ReplayResult
from testprotocols.models.firewall import (
    Chain,
    Connection,
    ConntrackStats,
    DefaultAction,
    FirewallRule,
    FirewallRuleAction,
    NatMode,
    NatRule,
    PortMapping,
    PortMappingProtocol,
    RuleCounters,
    Zone,
    ZonePolicy,
)
from testprotocols.models.impairment import (
    Blackout,
    Brownout,
    ImpairmentProfile,
    LatencySpike,
    PacketStorm,
    TransientEvent,
)
from testprotocols.models.l2_common import (
    MacTableEntry,
    StpGuard,
    StpMode,
    StpPortState,
)
from testprotocols.models.multicast import (
    GroupRecord,
    McastGroup,
    McastSource,
    MulticastGroupRecord,
    MulticastGroupRecordType,
)
from testprotocols.models.networking import (
    ArpEntry,
    DnsRecord,
    DnsRecordType,
    HTTPResult,
    HttpScheme,
    ICMPPacketData,
    IPAddresses,
    IpFamily,
    IpVersion,
    LinkAdminState,
    NmapPort,
    NmapPortState,
    NmapResult,
    PingResult,
    SnmpValueType,
)
from testprotocols.models.packets import RIPv2PacketData
from testprotocols.models.ports import PortRange
from testprotocols.models.qoe import (
    MeasurementSpec,
    PageCompletion,
    QoeCompletion,
    QoEResult,
    QoeScenario,
    QoeTool,
)
from testprotocols.models.radius import (
    RadiusAccountingRecord,
    RadiusServerConfig,
    RadiusSession,
    RadiusUser,
    ServiceStatus,
)
from testprotocols.models.sdwan_appliance import (
    ApplicationCategory,
    BgpConfig,
    BgpNeighbor,
    BgpPeerStatus,
    BgpSessionState,
    ContentCategory,
    DhcpLease,
    DhcpMode,
    DhcpOption,
    DhcpOptionType,
    DhcpReservation,
    FlowMatch,
    IntrusionConfig,
    IntrusionMode,
    IntrusionSensitivity,
    L3Rule,
    L7MatchType,
    L7Rule,
    MalwareConfig,
    MalwareMode,
    NatInboundAllow,
    OneToManyNatRule,
    OneToOneNatRule,
    PortForwardRule,
    ReservedRange,
    RuleAction,
    RuleProtocol,
    SecurityAction,
    SecurityEvent,
    ShapingPriority,
    ShapingRule,
    SiteToSiteVpnConfig,
    StaticRoute,
    SteeringScope,
    SyslogRole,
    SyslogServer,
    ThreatCategory,
    UplinkSelectionRule,
    UplinkState,
    UplinkStatus,
    UrlRules,
    VlanConfig,
    VpnHub,
    VpnPeerState,
    VpnPeerStatus,
    VpnRole,
    VpnSubnet,
)
from testprotocols.models.switch import (
    AccessPolicy,
    AccessPolicyType,
    AclDirection,
    AggregationMode,
    BindingSource,
    DiscoveryProtocol,
    Duplex,
    FhsBinding,
    FhsScope,
    FhsTrustState,
    LinkAggregationGroup,
    LinkState,
    LldpNeighbor,
    NtpServer,
    PoePortStatus,
    PoePriority,
    PoeStatus,
    PortAdminState,
    PortMode,
    PortStatusEntry,
    QosClassifier,
    QosRule,
    QosTrustMode,
    StormControlConfig,
    StormControlType,
    StormControlUnit,
    StpPortConfig,
    SwitchAclRule,
    SwitchPort,
    VlanDef,
)
from testprotocols.models.switch_routing import (
    InterfaceDhcpConfig,
    InterfaceMode,
    OspfConfig,
    OspfInterfaceSettings,
    OspfVersion,
    RedundancyGroup,
    RedundancyRole,
    RoutedInterface,
)
from testprotocols.models.tr069 import CpeConnectionStatus
from testprotocols.models.traffic import (
    IperfProcess,
    TrafficResult,
    TrafficSpec,
    TransportProtocol,
)
from testprotocols.models.voice import (
    MwiStatus,
    OfflineMessage,
    PhoneState,
    RtpStats,
)
from testprotocols.models.wan_edge import (  # type: ignore[deprecated]  # re-exported as released
    AppFlow,
    LinkHealthReport,
    LinkStatus,
    PathMetrics,
    RouteEntry,
    RouteOrigin,
    SLAPolicy,
    Telemetry,
    TrafficShapingRule,  # pyright: ignore[reportDeprecated]  # re-exported as released
    VPNPeerStatus,  # pyright: ignore[reportDeprecated]  # re-exported as released
)
from testprotocols.models.wifi import (
    ChannelWidth,
    MeshRole,
    MfpMode,
    WifiAcl,
    WifiAclMode,
    WifiBand,
    WifiBssConfig,
    WifiCaptiveConfig,
    WifiChannelUtilization,
    WifiDfsState,
    WifiMeshLink,
    WifiMeshNode,
    WifiMeshStatus,
    WifiMeshTopology,
    WifiNeighbor,
    WifiPhyMode,
    WifiRadioStats,
    WifiSecurityMode,
    WifiStation,
    WifiTransitionConfig,
)

__all__ = [
    # switch
    "AccessPolicy",
    "AccessPolicyType",
    "AclDirection",
    "AggregationMode",
    # wan_edge
    "AppFlow",
    # sdwan_appliance
    "ApplicationCategory",
    "ArpEntry",
    "BgpConfig",
    "BgpNeighbor",
    "BgpPeerStatus",
    "BgpSessionState",
    "BindingSource",
    "Blackout",
    "Brownout",
    "Chain",
    "ChannelWidth",
    # firewall
    "Connection",
    "ConntrackStats",
    "ContentCategory",
    # tr069
    "CpeConnectionStatus",
    # dhcp
    "DHCPTraceData",
    "DHCPV6TraceData",
    "DefaultAction",
    "DhcpLease",
    "DhcpLeaseObservation",
    "DhcpMode",
    "DhcpOption",
    "DhcpOptionType",
    "DhcpReservation",
    "DiscoveryProtocol",
    "DnsRecord",
    "DnsRecordType",
    "Duplex",
    # emission
    "EmitResult",
    "EventLogEntry",
    "FhsBinding",
    "FhsScope",
    "FhsTrustState",
    "FirewallRule",
    "FirewallRuleAction",
    "FlowMatch",
    # networking
    "GroupRecord",
    "HTTPResult",
    "HttpScheme",
    "ICMPPacketData",
    "IPAddresses",
    # impairment
    "ImpairmentProfile",
    # switch_routing
    "InterfaceDhcpConfig",
    "InterfaceMode",
    "IntrusionConfig",
    "IntrusionMode",
    "IntrusionSensitivity",
    "IpFamily",
    "IpVersion",
    "IperfProcess",
    "L3Rule",
    "L7MatchType",
    "L7Rule",
    "LatencySpike",
    "LinkAdminState",
    "LinkAggregationGroup",
    "LinkHealthReport",
    "LinkState",
    "LinkStatus",
    "LldpNeighbor",
    # l2_common
    "MacTableEntry",
    "MalwareConfig",
    "MalwareMode",
    # multicast
    "McastGroup",
    "McastSource",
    # qoe
    "MeasurementSpec",
    "MemoryUtilization",
    "MeshRole",
    "MfpMode",
    "MulticastGroupRecord",
    "MulticastGroupRecordType",
    # voice
    "MwiStatus",
    "NatInboundAllow",
    "NatMode",
    "NatRule",
    "NmapPort",
    "NmapPortState",
    "NmapResult",
    "NtpServer",
    "OfflineMessage",
    "OneToManyNatRule",
    "OneToOneNatRule",
    "OspfConfig",
    "OspfInterfaceSettings",
    "OspfVersion",
    "PacketStorm",
    "PageCompletion",
    "PathMetrics",
    "PhoneState",
    "PingResult",
    "PoePortStatus",
    "PoePriority",
    "PoeStatus",
    "PortAdminState",
    "PortForwardRule",
    "PortMapping",
    "PortMappingProtocol",
    "PortMode",
    "PortRange",
    "PortStatusEntry",
    "ProcessInfo",
    "QoEResult",
    "QoeCompletion",
    "QoeScenario",
    "QoeTool",
    "QosClassifier",
    "QosRule",
    "QosTrustMode",
    # packets
    "RIPv2PacketData",
    # radius
    "RadiusAccountingRecord",
    "RadiusServerConfig",
    "RadiusSession",
    "RadiusUser",
    "RedundancyGroup",
    "RedundancyRole",
    "ReplayResult",
    "ReservedRange",
    "RouteEntry",
    "RouteOrigin",
    "RoutedInterface",
    "RtpStats",
    "RuleAction",
    "RuleCounters",
    "RuleProtocol",
    "SLAPolicy",
    "SecurityAction",
    "SecurityEvent",
    "ServiceStatus",
    "ShapingPriority",
    "ShapingRule",
    "SiteToSiteVpnConfig",
    "SnmpValueType",
    "StaticRoute",
    "SteeringScope",
    "StormControlConfig",
    "StormControlType",
    "StormControlUnit",
    "StpGuard",
    "StpMode",
    "StpPortConfig",
    "StpPortState",
    "SwitchAclRule",
    "SwitchPort",
    "SyslogRole",
    "SyslogServer",
    "SyslogSeverity",
    "Telemetry",
    "ThreatCategory",
    # traffic
    "TrafficResult",
    "TrafficShapingRule",
    "TrafficSpec",
    "TransientEvent",
    "TransportProtocol",
    "UplinkSelectionRule",
    "UplinkState",
    "UplinkStatus",
    "UrlRules",
    "VPNPeerStatus",
    "VlanConfig",
    "VlanDef",
    "VpnHub",
    "VpnPeerState",
    "VpnPeerStatus",
    "VpnRole",
    "VpnSubnet",
    # wifi
    "WifiAcl",
    "WifiAclMode",
    "WifiBand",
    "WifiBssConfig",
    "WifiCaptiveConfig",
    "WifiChannelUtilization",
    "WifiDfsState",
    "WifiMeshLink",
    "WifiMeshNode",
    "WifiMeshStatus",
    "WifiMeshTopology",
    "WifiNeighbor",
    "WifiPhyMode",
    "WifiRadioStats",
    "WifiSecurityMode",
    "WifiStation",
    "WifiTransitionConfig",
    "Zone",
    "ZonePolicy",
]
