"""Shared data models for testprotocols."""

from __future__ import annotations

from testprotocols.models.dhcp import DhcpLeaseObservation, DHCPTraceData, DHCPV6TraceData
from testprotocols.models.emission import EmitResult, ReplayResult
from testprotocols.models.firewall import (
    Chain,
    Connection,
    ConnState,
    ConntrackStats,
    DefaultAction,
    FirewallRule,
    FirewallRuleAction,
    NatMode,
    NatRule,
    PortMapping,
    PortMappingProtocol,
    RuleCounters,
    Zone,
    ZonePolicy,
)
from testprotocols.models.impairment import ImpairmentProfile
from testprotocols.models.l2_common import (
    MacTableEntry,
    StpGuard,
    StpMode,
    StpPortState,
)
from testprotocols.models.multicast import (
    McastGroup,
    McastSource,
    MulticastGroupRecord,
    MulticastGroupRecordType,
)
from testprotocols.models.networking import HTTPResult, ICMPPacketData, IPAddresses
from testprotocols.models.packets import RIPv2PacketData
from testprotocols.models.ports import PortRange, format_port_ranges, parse_port_ranges, port_tuple
from testprotocols.models.qoe import MeasurementSpec, QoEResult
from testprotocols.models.radius import (
    RadiusAccountingRecord,
    RadiusServerConfig,
    RadiusSession,
    RadiusUser,
)
from testprotocols.models.sdwan_appliance import (
    ApplicationCategory,
    ApplicationMatch,
    BgpConfig,
    BgpNeighbor,
    BgpPeerStatus,
    BgpSessionState,
    CategoryMatch,
    ContentCategory,
    DhcpLease,
    DhcpMode,
    DhcpOption,
    DhcpOptionType,
    DhcpReservation,
    FlowMatch,
    HostMatch,
    IntrusionConfig,
    IntrusionMode,
    IntrusionSensitivity,
    IpRangeMatch,
    L3Rule,
    L7MatchType,
    L7Rule,
    MalwareConfig,
    MalwareMode,
    NatInboundAllow,
    OneToManyNatRule,
    OneToOneNatRule,
    PortForwardRule,
    PortMatch,
    ReservedRange,
    RuleAction,
    RuleProtocol,
    SecurityAction,
    SecurityEvent,
    ShapingPriority,
    ShapingRule,
    SiteToSiteVpnConfig,
    StaticRoute,
    SteeringScope,
    SyslogRole,
    SyslogServer,
    ThreatCategory,
    TrafficMatch,
    UplinkSelectionRule,
    UplinkState,
    UplinkStatus,
    VlanConfig,
    VpnHub,
    VpnPeerState,
    VpnPeerStatus,
    VpnRole,
    VpnSubnet,
    match_fields,
    traffic_match,
)
from testprotocols.models.switch import (
    AccessPolicy,
    AccessPolicyType,
    AclDirection,
    AggregationMode,
    BindingSource,
    DiscoveryProtocol,
    Duplex,
    FhsBinding,
    FhsScope,
    FhsTrustState,
    LinkAggregationGroup,
    LinkState,
    LldpNeighbor,
    NtpServer,
    PoePortStatus,
    PoePriority,
    PoeStatus,
    PortAdminState,
    PortMode,
    PortStatusEntry,
    QosRule,
    QosTrustMode,
    StormControlConfig,
    StormControlType,
    StpPortConfig,
    SwitchAclRule,
    SwitchPort,
    VlanDef,
)
from testprotocols.models.switch_routing import (
    InterfaceDhcpConfig,
    InterfaceMode,
    OspfConfig,
    OspfInterfaceSettings,
    OspfVersion,
    RedundancyGroup,
    RedundancyRole,
    RoutedInterface,
)
from testprotocols.models.tr069 import CpeConnectionStatus
from testprotocols.models.traffic import TrafficResult, TrafficSpec
from testprotocols.models.wan_edge import (
    AppFlow,
    LinkHealthReport,
    LinkStatus,
    PathMetrics,
    RouteEntry,
    RouteOrigin,
    SLAPolicy,
    TrafficShapingRule,
    VPNPeerStatus,
)
from testprotocols.models.wifi import (
    WifiAcl,
    WifiBssConfig,
    WifiCaptiveConfig,
    WifiChannelUtilization,
    WifiDfsState,
    WifiMeshLink,
    WifiMeshNode,
    WifiMeshStatus,
    WifiMeshTopology,
    WifiNeighbor,
    WifiRadioStats,
    WifiStation,
    WifiTransitionConfig,
)

__all__ = [
    # switch
    "AccessPolicy",
    "AccessPolicyType",
    "AclDirection",
    "AggregationMode",
    # wan_edge
    "AppFlow",
    # sdwan_appliance
    "ApplicationCategory",
    "ApplicationMatch",
    "BgpConfig",
    "BgpNeighbor",
    "BgpPeerStatus",
    "BgpSessionState",
    "BindingSource",
    "CategoryMatch",
    "Chain",
    # firewall
    "ConnState",
    "Connection",
    "ConntrackStats",
    "ContentCategory",
    # tr069
    "CpeConnectionStatus",
    # dhcp
    "DHCPTraceData",
    "DHCPV6TraceData",
    "DefaultAction",
    "DhcpLease",
    "DhcpLeaseObservation",
    "DhcpMode",
    "DhcpOption",
    "DhcpOptionType",
    "DhcpReservation",
    "DiscoveryProtocol",
    "Duplex",
    # emission
    "EmitResult",
    "FhsBinding",
    "FhsScope",
    "FhsTrustState",
    "FirewallRule",
    "FirewallRuleAction",
    "FlowMatch",
    # networking
    "HTTPResult",
    "HostMatch",
    "ICMPPacketData",
    "IPAddresses",
    # impairment
    "ImpairmentProfile",
    # switch_routing
    "InterfaceDhcpConfig",
    "InterfaceMode",
    "IntrusionConfig",
    "IntrusionMode",
    "IntrusionSensitivity",
    "IpRangeMatch",
    "L3Rule",
    "L7MatchType",
    "L7Rule",
    "LinkAggregationGroup",
    "LinkHealthReport",
    "LinkState",
    "LinkStatus",
    "LldpNeighbor",
    # l2_common
    "MacTableEntry",
    "MalwareConfig",
    "MalwareMode",
    # multicast
    "McastGroup",
    "McastSource",
    # qoe
    "MeasurementSpec",
    "MulticastGroupRecord",
    "MulticastGroupRecordType",
    "NatInboundAllow",
    "NatMode",
    "NatRule",
    "NtpServer",
    "OneToManyNatRule",
    "OneToOneNatRule",
    "OspfConfig",
    "OspfInterfaceSettings",
    "OspfVersion",
    "PathMetrics",
    "PoePortStatus",
    "PoePriority",
    "PoeStatus",
    "PortAdminState",
    "PortForwardRule",
    "PortMapping",
    "PortMappingProtocol",
    "PortMatch",
    "PortMode",
    "PortRange",
    "PortStatusEntry",
    "QoEResult",
    "QosRule",
    "QosTrustMode",
    # packets
    "RIPv2PacketData",
    # radius
    "RadiusAccountingRecord",
    "RadiusServerConfig",
    "RadiusSession",
    "RadiusUser",
    "RedundancyGroup",
    "RedundancyRole",
    "ReplayResult",
    "ReservedRange",
    "RouteEntry",
    "RouteOrigin",
    "RoutedInterface",
    "RuleAction",
    "RuleCounters",
    "RuleProtocol",
    "SLAPolicy",
    "SecurityAction",
    "SecurityEvent",
    "ShapingPriority",
    "ShapingRule",
    "SiteToSiteVpnConfig",
    "StaticRoute",
    "SteeringScope",
    "StormControlConfig",
    "StormControlType",
    "StpGuard",
    "StpMode",
    "StpPortConfig",
    "StpPortState",
    "SwitchAclRule",
    "SwitchPort",
    "SyslogRole",
    "SyslogServer",
    "ThreatCategory",
    "TrafficMatch",
    # traffic
    "TrafficResult",
    "TrafficShapingRule",
    "TrafficSpec",
    "UplinkSelectionRule",
    "UplinkState",
    "UplinkStatus",
    "VPNPeerStatus",
    "VlanConfig",
    "VlanDef",
    "VpnHub",
    "VpnPeerState",
    "VpnPeerStatus",
    "VpnRole",
    "VpnSubnet",
    # wifi
    "WifiAcl",
    "WifiBssConfig",
    "WifiCaptiveConfig",
    "WifiChannelUtilization",
    "WifiDfsState",
    "WifiMeshLink",
    "WifiMeshNode",
    "WifiMeshStatus",
    "WifiMeshTopology",
    "WifiNeighbor",
    "WifiRadioStats",
    "WifiStation",
    "WifiTransitionConfig",
    "Zone",
    "ZonePolicy",
    # ports
    "format_port_ranges",
    "match_fields",
    "parse_port_ranges",
    "port_tuple",
    "traffic_match",
]
