"""Shared data models for palco-templates."""

from __future__ import annotations

from testprotocols.models.dhcp import DHCPTraceData, DHCPV6TraceData
from testprotocols.models.firewall import (
    Connection,
    ConntrackStats,
    FirewallRule,
    NatRule,
    PortMapping,
    Zone,
    ZonePolicy,
)
from testprotocols.models.impairment import ImpairmentProfile
from testprotocols.models.multicast import (
    McastGroup,
    McastSource,
    MulticastGroupRecord,
    MulticastGroupRecordType,
)
from testprotocols.models.networking import HTTPResult, ICMPPacketData, IPAddresses
from testprotocols.models.packets import RIPv2PacketData
from testprotocols.models.qoe import MeasurementSpec, QoEResult
from testprotocols.models.sdwan_appliance import (
    ApplicationCategory,
    BgpConfig,
    BgpNeighbor,
    BgpPeerStatus,
    BgpSessionState,
    ContentCategory,
    DhcpLease,
    DhcpMode,
    DhcpOption,
    DhcpOptionType,
    DhcpReservation,
    FlowMatch,
    IntrusionConfig,
    IntrusionMode,
    IntrusionSensitivity,
    L3Rule,
    L7MatchType,
    L7Rule,
    MalwareConfig,
    MalwareMode,
    NatInboundAllow,
    OneToManyNatRule,
    OneToOneNatRule,
    PortForwardRule,
    RuleAction,
    RuleProtocol,
    SecurityAction,
    SecurityEvent,
    ShapingPriority,
    ShapingRule,
    SiteToSiteVpnConfig,
    StaticRoute,
    SteeringScope,
    SyslogRole,
    SyslogServer,
    ThreatCategory,
    UplinkSelectionRule,
    UplinkState,
    UplinkStatus,
    VlanConfig,
    VpnHub,
    VpnPeerState,
    VpnPeerStatus,
    VpnRole,
    VpnSubnet,
)
from testprotocols.models.l2_common import (
    MacTableEntry,
    StpGuard,
    StpMode,
    StpPortState,
)
from testprotocols.models.switch import (
    AccessPolicy,
    AccessPolicyType,
    AclDirection,
    AggregationMode,
    BindingSource,
    DiscoveryProtocol,
    Duplex,
    FhsBinding,
    FhsScope,
    FhsTrustState,
    LinkAggregationGroup,
    LinkState,
    LldpNeighbor,
    NtpServer,
    PoePortStatus,
    PoePriority,
    PoeStatus,
    PortAdminState,
    PortMode,
    PortStatusEntry,
    QosRule,
    QosTrustMode,
    StormControlConfig,
    StormControlType,
    StpPortConfig,
    SwitchAclRule,
    SwitchPort,
    VlanDef,
)
from testprotocols.models.radius import (
    RadiusAccountingRecord,
    RadiusServerConfig,
    RadiusSession,
    RadiusUser,
)
from testprotocols.models.tr069 import CpeConnectionStatus
from testprotocols.models.traffic import TrafficResult, TrafficSpec
from testprotocols.models.switch_routing import (
    InterfaceDhcpConfig,
    InterfaceMode,
    OspfConfig,
    OspfInterfaceSettings,
    OspfVersion,
    RedundancyGroup,
    RedundancyRole,
    RoutedInterface,
)
from testprotocols.models.wan_edge import (
    AppFlow,
    LinkHealthReport,
    LinkStatus,
    PathMetrics,
    RouteEntry,
    RouteOrigin,
    SLAPolicy,
    TrafficShapingRule,
    VPNPeerStatus,
)
from testprotocols.models.wifi import (
    WifiAcl,
    WifiBssConfig,
    WifiCaptiveConfig,
    WifiChannelUtilization,
    WifiDfsState,
    WifiMeshLink,
    WifiMeshNode,
    WifiMeshStatus,
    WifiMeshTopology,
    WifiNeighbor,
    WifiRadioStats,
    WifiStation,
    WifiTransitionConfig,
)

__all__ = [
    # l2_common
    "MacTableEntry",
    "StpGuard",
    "StpMode",
    "StpPortState",
    # switch
    "AccessPolicy",
    "AccessPolicyType",
    "AclDirection",
    "AggregationMode",
    "BindingSource",
    "DiscoveryProtocol",
    "Duplex",
    "FhsBinding",
    "FhsScope",
    "FhsTrustState",
    "LinkAggregationGroup",
    "LinkState",
    "LldpNeighbor",
    "NtpServer",
    "PoePortStatus",
    "PoePriority",
    "PoeStatus",
    "PortAdminState",
    "PortMode",
    "PortStatusEntry",
    "QosRule",
    "QosTrustMode",
    "StormControlConfig",
    "StormControlType",
    "StpPortConfig",
    "SwitchAclRule",
    "SwitchPort",
    "VlanDef",
    # switch_routing
    "InterfaceDhcpConfig",
    "InterfaceMode",
    "OspfConfig",
    "OspfInterfaceSettings",
    "OspfVersion",
    "RedundancyGroup",
    "RedundancyRole",
    "RoutedInterface",
    # wan_edge
    "AppFlow",
    # firewall
    "Connection",
    "ConntrackStats",
    # tr069
    "CpeConnectionStatus",
    # dhcp
    "DHCPTraceData",
    "DHCPV6TraceData",
    "FirewallRule",
    # networking
    "HTTPResult",
    "ICMPPacketData",
    "IPAddresses",
    # impairment
    "ImpairmentProfile",
    # sdwan_appliance
    "ApplicationCategory",
    "BgpConfig",
    "BgpNeighbor",
    "BgpPeerStatus",
    "BgpSessionState",
    "ContentCategory",
    "DhcpLease",
    "DhcpMode",
    "DhcpOption",
    "DhcpOptionType",
    "DhcpReservation",
    "FlowMatch",
    "IntrusionConfig",
    "IntrusionMode",
    "IntrusionSensitivity",
    "L3Rule",
    "L7MatchType",
    "L7Rule",
    "MalwareConfig",
    "MalwareMode",
    "NatInboundAllow",
    "OneToManyNatRule",
    "OneToOneNatRule",
    "PortForwardRule",
    "RuleAction",
    "RuleProtocol",
    "SecurityAction",
    "SecurityEvent",
    "ShapingPriority",
    "ShapingRule",
    "SiteToSiteVpnConfig",
    "StaticRoute",
    "SteeringScope",
    "SyslogRole",
    "SyslogServer",
    "ThreatCategory",
    "UplinkSelectionRule",
    "UplinkState",
    "UplinkStatus",
    "VlanConfig",
    "VpnHub",
    "VpnPeerState",
    "VpnPeerStatus",
    "VpnRole",
    "VpnSubnet",
    "LinkHealthReport",
    "LinkStatus",
    # multicast
    "McastGroup",
    "McastSource",
    # qoe
    "MeasurementSpec",
    "MulticastGroupRecord",
    "MulticastGroupRecordType",
    "NatRule",
    "PathMetrics",
    "PortMapping",
    "QoEResult",
    # packets
    "RIPv2PacketData",
    # radius
    "RadiusAccountingRecord",
    "RadiusServerConfig",
    "RadiusSession",
    "RadiusUser",
    "RouteEntry",
    "RouteOrigin",
    "SLAPolicy",
    # traffic
    "TrafficResult",
    "TrafficShapingRule",
    "TrafficSpec",
    "VPNPeerStatus",
    # wifi
    "WifiAcl",
    "WifiBssConfig",
    "WifiCaptiveConfig",
    "WifiChannelUtilization",
    "WifiDfsState",
    "WifiMeshLink",
    "WifiMeshNode",
    "WifiMeshStatus",
    "WifiMeshTopology",
    "WifiNeighbor",
    "WifiRadioStats",
    "WifiStation",
    "WifiTransitionConfig",
    "Zone",
    "ZonePolicy",
]
